version: "3.9"

services:
  mysql:
    image: mysql:5.7.22
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      SERVICE_NAME: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - ./public:/var/www/html
      - .:/var/www
      - ./app:/var/www/app
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SERVICE_NAME: mysql
      CONTAINER_ROLE: app
  
  queue:
    image: tunga-dd-6_app:latest
    environment: 
      CONTAINER_ROLE: queue
    depends_on:
      - app
    volumes: 
      - .:/var/www

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - 3001:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
  redis:
    image: redis:6.2.4-alpine
